//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaleShoes
{
    using System;
    using System.Collections.Generic;
    
    public partial class KhuyenMai_Hang
    {
        public int Id { get; set; }
        public Nullable<int> MaKhuyenMai { get; set; }
        public Nullable<int> MaHangGiay { get; set; }
    
        public virtual HangGiay HangGiay { get; set; }
        public virtual KhuyenMai KhuyenMai { get; set; }
    }
}
